// Generated by GraphWalker (http://www.graphwalker.org)

import org.graphwalker.java.annotation.*;

@Model(file = "test.json")
interface tp6 {

    @Vertex()
    void v_filled();

    @Vertex()
    void v_empty();

    @Vertex()
    void v_overflow();

    @Vertex()
    void v_partiallyFilled();

    @Vertex()
    void v_start();

    @Edge()
    void e_Union(OrdSet s1, OrdSet s2);

//    @Edge()
//    void e_OrdSet(int[] v);

    @Edge()
    void e_OrdSet(int[] v);

//    @Edge()
//    void e_Union(OrdSet s1, Ordset s2);

//    @Edge()
//    void e_Remove(int val);

    @Edge()
    void e_Remove(int val);

    @Edge()
    void e_Add(int n);

//    @Edge()
//    void e_Remove(int val);
//
//    @Edge()
//    void e_Remove(int val);
//
//    @Edge()
//    void e_Add(int n);
//
//    @Edge()
//    void e_Add(int n);
//
//    @Edge()
//    void e_Add(int n);
//
//    @Edge()
//    void e_Add(int n);
//
//    @Edge()
//    void e_OrdSet(int[] v);
//
//    @Edge()
//    void e_Remove(int val);
//
//    @Edge()
//    void e_Remove(int val);
//
//    @Edge()
//    void e_Add(int n);

    @Edge()
    void e_OrdSet(int n);
//
//    @Edge()
//    void e_Union(OrdSet s1, OrdSet s2);
//
//    @Edge()
//    void e_OrdSet(int[] v);


}
